### ISSUE TITLE
Stuck at initializing

### ISSUE THREAD

**Issue by gaetschwartz** [gaetschwartz/build-runner#1]
## Copy from https://github.com/gaetschwartz/freezed/issues/3

When using watch from status bar it keeps initializing. It never completes while `flutter pub run build_runner watch --delete-conflicting-outputs` works fine.

Also generating freezed class give error:
```Command 'Freezed: Generate a new Freezed class' resulted in an error (Running the contributed command: 'freezed.generate' failed.)```

I think problem is with my IDE maybe. 

```
Code - OSS
Version: 1.54.2
Commit: fd6f3bce6709b121a895d042d343d71f317d74e7
Date: 2021-03-12T19:27:39.374Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.11.7-arch1-1
```

---

Initially filed by @2shrestha22.
@yerzhant and @craigomac also commented.

**Comment by gaetschwartz** [comment]
Hi @2shrestha22, does this fix your issue ?

**Comment by 2shrestha22** [comment]
haven't tried yet, I will and inform you.

**Comment by 2shrestha22** [comment]
Hi @gaetschwartz would you please tell me how can I download this? I can't find it at https://marketplace.visualstudio.com/items?itemName=blaxou.build-runner. It gives 404 not found error.

**Comment by gaetschwartz** [comment]
Hi @2shrestha22 , where did you find this link ? This is the old extension ID, you can get the extension here: https://marketplace.visualstudio.com/items?itemName=GaetSchwartz.build-runner

**Comment by 2shrestha22** [comment]
that link was in freezed extension page.

**Comment by 2shrestha22** [comment]
Failing to determine where to run the code. After choosing a folder gives `Command exited with code -2`.

![build_runner](https://user-images.githubusercontent.com/24835256/115110713-76190d80-9f9c-11eb-91f0-ab8477fb38e8.gif)

**Comment by gaetschwartz** [comment]
Hi, watching is still broken on some platforms (only tested on MacOS and you seem to be using Linux), I published a new version (0.2.6) which should log exactly where and which command it spawns to make sure it works well. Can you give it a try ?

**Comment by 2shrestha22** [comment]
```
Spawning `dart run build_runner watch` in /home/hatman/flutter_projects/barcode_scanner

Command exited with code -2
```

**Comment by gaetschwartz** [comment]
Did you try running this command on the terminal, does it work ? Is `dart` in your `PATH` ?

**Comment by 2shrestha22** [comment]
Here is the result:
```
➜  barcode_scanner git:(master) ✗ dart run build_runner watch
Could not find a file named "pubspec.yaml" in "/home/hatman/.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-20.0.0".
```
I have build runner in pubspec.yaml
```
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  flutter_native_splash: ^1.1.7+1
  freezed: ^0.14.1+2
```
`flutter pub run build_runner watch` works fine

**Comment by gaetschwartz** [comment]
It is an issue with dart then, I'm not entirely sure as of why this happens but maybe try `dart pub cache repair; flutter pub get` ?

**Comment by 2shrestha22** [comment]
I found similar issue in Github/Dart. I will try that tomorrow and will inform you the result.

Does this require pub cache to be in path?

**Comment by gaetschwartz** [comment]
Ff dart is in the path, it's okayx.

**Comment by veresvit** [comment]
Hi, I have the same problem as @2shrestha22 . The previous freezed extension launched Build runner fine, now after migration to your extension I am not able to get it going. I am using MacOS and terminal command works well. Dart is in the path. Both Watch and the Shortcut (CMD+Shift+B) doesn't work (asks to select a folder where to run and fails with the same error as for 2shrestha22).

Thank you for this extension, looking forward to use it in the future. :)

**Comment by gaetschwartz** [comment]
Hi @veresvit, does `dart run build_runner build` work when typed in the terminal ? If no it seems to be a dart issue. I had this a few times too. Usually deleting `pub`'s cache works. I might add an option to run the different commands using `flutter pub run` instead of `dart run` which will probably fix the issue.

**Comment by veresvit** [comment]
@gaetschwartz  You are right. The `dart run` command does not work, but the `flutter packages run` does. I did try cache repair before this.

```
dart run build_runner build                                                              
Could not find a file named "pubspec.yaml" in "/Users/veres/.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-19.0.0".
```

**Comment by gaetschwartz** [comment]
Hi @veresvit, I added propper flutter support in the latest version `0.3.0` I just released. You can now choose whether you want to use `flutter` or `dart` to run commands, and choose `flutter` in the settings in your case :)

**Comment by 2shrestha22** [comment]
After deleting `/home/my_username/.pub-cache` folder and `.packages` from root of my project folder then running `dart pub get`, `dart run build_runner watch` is working fine. However extension still asks for folder and gives the same previous output.
```
Spawning `flutter pub run build_runner watch` in /home/hatman/flutter_projects/barcode_scanner

Command exited with code -2
```
Build Runner version: 0.3.0
Another question, why extension is failing to determine the location to run build_runner command? Is this only happening to us or is normal?

**Comment by gaetschwartz** [comment]
> Spawning `flutter pub run build_runner watch` in /home/hatman/flutter_projects/barcode_scanner
> 
> Command exited with code -2
What does running `flutter pub run build_runner watch` do, does it fail or not ? 

> Another question, why extension is failing to determine the location to run build_runner command? Is this only happening to us or is normal?
Not normal indeed, but I don't have a linux machine so it's hard for me to debug it, will see if I have time to try on a VM. Can't promise anything because of school though.

**Comment by 2shrestha22** [comment]
@gaetschwartz `flutter pub run build_runner watch` and `dart pub run build_runner watch` works fine.

**Comment by gaetschwartz** [comment]
You can try to debug it by yourself by cloning the repository, opening it in VSCode and then opening `src/extension.ts`. Thne press `F5` to run the extension. A new window named "[Extension Development Host] ..." will open. Open your project on it and try using `CTRL+SHIFT+B`. You can then check the Debug Console on the main window and should see debug informations.

**Comment by gaetschwartz** [comment]
Hi @2shrestha22 I think I've been able to pinpoint the issue here, I forgot to handle an edge case. Now it should work fine hopefully. Check `0.3.1` and tell me if it's working !

**Comment by 2shrestha22** [comment]
@gaetschwartz I did what you told to debug myself but I don't know js and all the thing needed to debug the extension. So I have attached the log from debug console.
`ctrl+shift+B` - this time it stuck saying initializing.
```
document_path=/home/hatman/flutter_projects/barcode_scanner/lib/main.dart
workspaceName=barcode_scanner
workspacePath=/home/hatman/flutter_projects/barcode_scanner
segments=lib
Looking for /home/hatman/flutter_projects/barcode_scanner/pubspec.yaml
Found it!
cwd=/home/hatman/flutter_projects/barcode_scanner
Spawning `flutter pub run build_runner build --delete-conflicting-outputs` in /home/hatman/flutter_projects/barcode_scanner
Ran flutter pub run build_runner build --delete-conflicting-outputs
```
`clicking the watch button` - gave error code - 2 as before.
```
document_path=/home/hatman/flutter_projects/barcode_scanner/lib/main.dart
workspaceName=barcode_scanner
workspacePath=/home/hatman/flutter_projects/barcode_scanner
segments=lib
Looking for /home/hatman/flutter_projects/barcode_scanner/pubspec.yaml
Found it!
cwd: /home/hatman/flutter_projects/barcode_scanner
Spawning `flutter pub run build_runner watch --delete-conflicting-outputs` in /home/hatman/flutter_projects/barcode_scanner
Started with PID: undefined
Error: spawn flutter ENOENT
	at Process.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
close: -2
```

**Comment by gaetschwartz** [comment]
`ENOENT` means that either `/home/hatman/flutter_projects/barcode_scanner` is not a directory or `flutter` is not in the path, weird. Both should be correct isn't it ?

**Comment by 2shrestha22** [comment]
Yes flutter is in my path and dart too. And directory is also correct.

**Comment by gaetschwartz** [comment]
That's rather weird, will try to investigate on a VM today.

**Comment by 2shrestha22** [comment]
I don't know what I did but have tried replacing cmd with npm `this.process = cp.spawn(`npm`, args, opts);` and seems it detects the `npm` command also tried `ping` that command also runs but with `flutter` or `dart` gives `ENOENT`.

I have `bash` and `zsh` installed. In both `flutter` and `dart` works.

**Comment by 2shrestha22** [comment]
I think I found something, - https://stackoverflow.com/questions/18846918/node-js-error-spawn-enoent someone says "Simply replacing spawn by exec fixed all of my problems (linux binary in PATH with permissions wouldn't execute)"
and similar problem here - https://stackoverflow.com/questions/17516772/using-nodejss-spawn-causes-unknown-option-and-error-spawn-enoent-err.
Does that mean `flutter` binary is not set as executable?

**Comment by 2shrestha22** [comment]
One more thing, with absolute path it is working (starts watching), `cmd` replaced with full path to flutter `/opt/flutter/bin/flutter`.

**Comment by gaetschwartz** [comment]
Did you install using `snap` ? If yes that's the reason, `flutter` is actually not in the path. I published `0.3.2` that allows you to specify flutter's path. I tried on a linux VM and managed to reproduce your issue. Make sure to set it to the executable's path, you can use this command to obtain it.
```bash
echo "$(flutter sdk-path)/bin/flutter"
```

**Comment by 2shrestha22** [comment]
No, I don't use snap. I have installed Flutter manually.
In zsh:
```
➜  ~ which flutter
/opt/flutter/bin/flutter
➜  ~ which dart   
/opt/flutter/bin/dart
➜  ~ 
```
in bash:
```
hatman@Mystique:[~]: which flutter
/opt/flutter/bin/flutter
hatman@Mystique:[~]: which dart
/opt/flutter/bin/dart
hatman@Mystique:[~]: 
```
both `flutter` and `dart` are available. Have you looked at these issues in stackoverflow?

> I think I found something, - https://stackoverflow.com/questions/18846918/node-js-error-spawn-enoent someone says "Simply replacing spawn by exec fixed all of my problems (linux binary in PATH with permissions wouldn't execute)"
> and similar problem here - https://stackoverflow.com/questions/17516772/using-nodejss-spawn-causes-unknown-option-and-error-spawn-enoent-err.
> Does that mean `flutter` binary is not set as executable?
> [edit] No, `flutter` is already executable without executable permission it won't run in terminal.



> One more thing, with absolute path it is working (starts watching), `cmd` replaced with full path to flutter `/opt/flutter/bin/flutter`.
> I hope you will soon find the solution for this.
> https://stackoverflow.com/questions/48212009/how-to-run-executable-file-in-ubuntu-as-a-command-or-service-with-node-js-child

and since I don't use snap `echo "$(flutter sdk-path)/bin/flutter"` does not work, `Could not find a command named "sdk-path"`.

**Comment by gaetschwartz** [comment]
If you specify the flutter executable path as `/opt/flutter/bin/flutter` it works right ?

**Comment by 2shrestha22** [comment]
> If you specify the flutter executable path as `/opt/flutter/bin/flutter` it works right ?

Yes it works.

**Comment by gaetschwartz** [comment]
Then I don't see what the issue is ? I will try seeing if `exec` fixes it, thanks for the research !

**Comment by gaetschwartz** [comment]
@2shrestha22 On the new version `0.3.3` it seems to work fine. At least I'm unable to reproduce when flutter is installed manually and **in path**. Worst case scenario just specify flutter's path in the settings and this should get you going.



https://user-images.githubusercontent.com/25441359/115278231-81f40380-a145-11eb-9957-86b9a5cd73a5.mp4

**Comment by 2shrestha22** [comment]
Thank you.

**Comment by 2shrestha22** [comment]
I found what is the problem. I have added `flutter` in my path in `.zshrc` using `export PATH="$PATH:/opt/flutter/bin"` so trying to log `process.env.PATH`, `console.log('PATH in process.env.PATH is\' ${process.env.PATH}' );` gives all other path except `flutter`.

Is there any way to fix this so that user should not have to set PATH globally?

**Comment by veresvit** [comment]
> Hi @veresvit, I added proper `flutter` support in the latest version `0.3.0` I just released. You can now choose whether you want to use `flutter` or `dart` to run commands. Choose `flutter` in the settings in your case :)

Hi, sorry for late reply, now with the version 0.3.3 works everything well on my setup with MacOS for Flutter. Can't speak for pure dart. Thank you so much.

**Comment by gaetschwartz** [comment]
> Hi, sorry for late reply, now with the version 0.3.3 works everything well on my setup with MacOS for Flutter. Can't speak for pure dart. Thank you so much.

@veresvit No worries, glad I could help ☺

>  found what is the problem. I have added flutter in my path in .zshrc using export PATH="$PATH:/opt/flutter/bin" so trying to log process.env.PATH, console.log('PATH in process.env.PATH is\' ${process.env.PATH}' ); gives all other path except flutter.
Is there any way to fix this so that user should not have to set PATH globally?

@2shrestha22 `chilld_process` uses `bash` as a default shell on linux, so you should add flutter to `bash`' `$PATH`. You can do so by creating a `.bashrc` file in `~/` and putting the same content you put in `.zshrc`.

**Comment by 2shrestha22** [comment]
Thanks, I will try that.

**Comment by gaetschwartz** [comment]
Hi @2shrestha22, have you had time to try ?

**Comment by 2shrestha22** [comment]
I haven't added PATH in bash, but using with setting PATH in extension setting. And it works fine.

**Comment by erayerdin** [comment]
Mine exits with a different exit code saying:

```plain
Spawning `flutter pub run build_runner watch` in `/home/erayerdin/Documents/Projects/Programming/programmatic`

Command exited with code 255
```

**Comment by erayerdin** [comment]
Strangely, I have tried it with a fresh Linux installation and it does not work. It's the same behavior as below.

I never get it to working, so I do it on terminal.

> Mine exits with a different exit code saying:
> 
> ```
> Spawning `flutter pub run build_runner watch` in `/home/erayerdin/Documents/Projects/Programming/programmatic`
> 
> Command exited with code 255
> ```
> 
> Environment
> * Ubuntu 20.04
> * VSCode 1.59.1

**Comment by Musta-Pollo** [comment]
For my worked to set in settings.json:

`"build-runner.flutterPath": "/home/musta-pollo/development/flutter/bin/flutter",`

Thanks for the discussion above!

**Comment by lucavenir** [comment]
I think this workaround should be mentioned in extension readme / home page. I had a bad time finding this discussion.
