### ISSUE TITLE
Command 'Freezed: Build with build_runner' resulted in an error (command 'freezed.build_runner_build' not found)

### ISSUE THREAD

**Issue by iulian0512** [gaetschwartz/build-runner#2]
How should i diagnose this issue with the extension ? running flutter packages pub run build_runner build --delete-conflicting-outputs works fine generates fine. 
Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by iulian0512** [comment]
works fine now, many thanks.

**Comment by gaetschwartz** [comment]
Glad it does ! ☺
