### ISSUE TITLE
Command Build Runner: Build not found

### ISSUE THREAD

**Issue by s9th** [gaetschwartz/build-runner#7]
![image](https://user-images.githubusercontent.com/15362801/138907189-bd2210d5-cc85-4084-b67c-6e9855d13361.png)

Hi,

The error on the screenshot started happening recently. I cannot pinpoint the exact time and place when it started, it could have been latest VSCode update.

I've tried reinstalling the extension and doing flutter clean but to no avail. The build runner command from integrated terminal works fine.

**Comment by gaetschwartz** [comment]
Hi, sorry for the delayed answer, I was on holidays. I'll try fixing that today, I also encounter that error.

**Comment by gaetschwartz** [comment]
Should be fixed in 0.7.0 !
