### ISSUE TITLE
Add support for flutter version manager

### ISSUE THREAD

**Issue by s9th** [gaetschwartz/build-runner#9]
When using flutter version manager (fvm.app) the build_runner extension doesn't work since flutter executable is not in the path and command 'fvm flutter' should be used instead of 'flutter.

Please consider allowing 'fvm flutter' in the list of available commands or allowing to edit the command in settings.json with arbitrary values

**Comment by s9th** [comment]
Closing since it was a PATH issue on my end

**Comment by gaetschwartz** [comment]
This seems to be resolved, feel free to reopen it if you need.

**Comment by cv0cv0** [comment]
> 我fvm工作，通过加fvm文件夹中的位置的设置。json
> 
> ```
> 
>   "build-runner.flutterPath": ".fvm/flutter_sdk/bin/flutter",
> ```

'.fvm' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
